### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by adishardiseffectris** [coolsam726/jetstream-inertia-generator#19]
Any plans on supporting PHP 8! 

Really diggin what I'm seeing here and PHP 8 support would be awesome!

Cheers!

**Comment by coolsam726** [comment]
@adishardiseffectris thanks alot. PHP 8 support is definitely coming. It's a bit of work since I will have to refractor all the generators so that any generated code is php8 compatible, but that's what's currently on my plate.

I'm also willing to collaborate, if anyone would be interested and willing to spare some time 😊
