### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by asbator** [coolsam726/jetstream-inertia-generator#25]
Step 11
Installation process is missing module vite/dynamic-import-polyfill

I've installed it as /dynamic-import-polyfill and updated /resources/scripts/main.ts accordingly.
I guess it works same as vite module.

---------------------

Also code inside resources/js/app.js seems to be wrong (consists require command) or missing requirejs module.
The app is throwing :
Uncaught ReferenceError: require is not defined    at app.js:1

**Comment by coolsam726** [comment]
@asbator this is well noted. A bit of refactoring that needs to be done: 
- Remove the `app.js` because we no longer need it after moving the project to ViteJS and typescript.
- Add the `dynamic-import-polyfill` to the list of npm dependencies in the documentation.
Thanks for noting these. Do you mind a PR please?
