### ISSUE TITLE
enum data type

### ISSUE THREAD

**Issue by abhitheawesomecoder** [coolsam726/jetstream-inertia-generator#43]
support for enum datatype

**Comment by coolsam726** [comment]
Enums are supported by default in PHP 8.1 We will support php 8.1 in our next release and that should fix this issue.

**Comment by coolsam726** [comment]
@abhitheawesomecoder I don't think I had understood your issue. You must have meant the enum database type. This issue is due to the fact that Doctrine/DBAL does not support enum data type.
The workaround is to add the following to one of your service providers:
```php
use Doctrine\DBAL\Types\StringType;
use Doctrine\DBAL\Types\Type;
use Illuminate\Support\Facades\DB;

    public function __construct()
    {
        if (! Type::hasType('enum')) {
            Type::addType('enum', StringType::class);
        }
        // For point types
        // DB::getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('point', 'string');
        DB::getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');
    }
```
I will do a PR to add this to the jig service provider.

Take a look at [this answer](https://stackoverflow.com/questions/33140860/laravel-5-1-unknown-database-type-enum-requested) for more details:
